### ISSUE TITLE
Mock-up of the UI

### ISSUE THREAD

**Issue by coszio** [fcossio/FiberDiameter#2]
# Definition of success
A Figma of the UI will show what we will strive for in the React implementation. For now we have the quick layout made in the [project document](https://docs.google.com/document/d/1XOpTKn8M-a2v3Yqfd23TqrJEocUZrsKVwOnOUlDlc9A). 

Approval from @yaelsuarez is preferred.

**Comment by coszio** [comment]
Figma link is here:

https://www.figma.com/file/31yL3Iy70t8S8YDskvDIco/Untitled?node-id=0%3A1

**Comment by coszio** [comment]
@yaelsuarez, @fcossio Some basic features are being displayed now, is there anything else you may want to include? I don't know if the automatic detection is parameterizable, in such case we should contemplate this in the UI.

**Comment by yaelsuarez** [comment]
@coszioSome comments:
- The average of all the fibers above the section of the average of each fiber could be added (Global avg diameter)
- I think a better word for adjust scale could be 'Set scale'. Where the user can draw a line (on the reference line of the image) and write to how many nanometers the legth of the line corresponds 
- Would be cool to download the annotated image.

**Comment by coszio** [comment]
Thanks @yaelsuarez 

- > - The average of all the fibers above the section of the average of each fiber could be added (Global avg diameter)

    Agreed, added a new global section in a VSCode style on the left. 

- > -  I think a better word for adjust scale could be 'Set scale'. Where the user can draw a line (on the reference line of the image) and write to how many nanometers the legth of the line corresponds

     That's exactly what I was thinking the `scale` action would do.

- > - Would be cool to download the annotated image.

    That's a feature we could delegate for a future release, but I'll add it anyway to keep it in the wish list

Any other wishes/comments/renames are gladly appreciated.

**Comment by fcossio** [comment]
I think this can be considered as Done 👍
